language: c

branches:
  only:
    - base

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      compiler: gcc

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - valgrind
            - cppcheck
            - gcc-7
            - g++-7
            - lcov

before_install:
  - sudo apt-get -y install valgrind
  - pip install --user cpp-coveralls

script:
  - export CXX=/usr/bin/g++-7
  - export C=/usr/bin/gcc-7
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest --output-on-failure
  - valgrind --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./tests/Google_Tests_run
  - cppcheck --enable=all --std=c99 --check-config --suppress=missingIncludeSystem ../library/library.c ../library/lib_includes.h


after_success:
  - coveralls --root .. --build-root . -E ".*CMakeFiles.*" -E ".*googletest*" --gcov /usr/bin/gcov --gcov-options '\-lp'