#ifndef TP_C_TASK_2_CONFIG_H
#define TP_C_TASK_2_CONFIG_H

#define DEFAULT_MODULE 1024
#define DEFAULT_ARRAY_SIZE 30000000
#define MEASURE_TIME_ITERATIONS 10
#define DEFAULT_INPUT_TXT "data_test_input.txt"
#define DEFAULT_ARRAY_VALUE_FOR_TEST 3

#endif //TP_C_TASK_2_CONFIG_H
